### ISSUE TITLE
How connect to rocketchat?

### ISSUE THREAD

**Issue by alexleosumy** [croz-ltd/Rocket.Chat.App-Remind#1]
Hello 
need instructions how to connect your project to rocketchat

**Comment by mjovanovic0** [comment]
Currently application is not submitted to Rocket.Chat marketplace - pending.

Firstly we need to wait for Rocket.Chat 3.8 official release (unless you are running RC in prod).

As app is not on marketplace, only way currently is to compile it manually and deploy on you instance. Be aware that your instance must be version >=3.8.0-rc.0.

Steps for manual compile and deploy:

```
npm install -g @rocket.chat/apps-cli
git clone https://github.com/mjovanovic0/rocketchat-remind-app
cd rocketchat-remind-app
rc-apps deploy --url <instance_url> --username <username>  --password <password>
```

Note that user that you provide to `rc-apps deploy` needs to have admin rights to be able to deploy apps. Also, application framework must be enabled, and Enable development mode needs to be enabled.

**Comment by mjovanovic0** [comment]
App is published to official Rocket.Chat Marketplace
