### ISSUE TITLE
Problem triggering jobs

### ISSUE THREAD

**Issue by thassiov** [croz-ltd/Rocket.Chat.App-Remind#10]
https://github.com/croz-ltd/Rocket.Chat.App-Remind/blob/e8545a64fb44fe10eb71edc6ce6c51c6491a9d4a/src/Command/RemindCommand.ts#L70

This line references a unknown processor id `hey`, but the registered processor is called `remind-app`:

https://github.com/croz-ltd/Rocket.Chat.App-Remind/blob/e8545a64fb44fe10eb71edc6ce6c51c6491a9d4a/RemindApp.ts#L16

Adjusting the `RemindCommand.ts` code to reference the same id fixes the issue. This was tested with RocketChat v3.9.7 and v3.11.1

## Tests

- Install app as is (git clone, npm install, rc-apps deploy)
   - Scheduling jobs do not work (but receive confirmation via message)
- Disable/enable app (clears any app's data from the scheduler system)
   - Scheduling jobs do not work (but receive confirmation via message)
- Uninstall/reinstall the app as is
   - Scheduling jobs do not work (but receive confirmation via message)
- Uninstall and reinstall it with the change in the processor id mentioned above
   - Scheduling jobs work as expected (correct behavior)
- Disable/enable app (clears any app's data from the scheduler system)
   - Scheduling jobs work as expected (correct behavior)
- Uninstall/reinstall the app removing the modifications
   - Scheduling jobs do not work (but receive confirmation via message)
- Disable/enable app (clears any app's data from the scheduler system)
   - Scheduling jobs do not work (but receive confirmation via message)

**Comment by mjovanovic0** [comment]
Thanks you @thassiov :)

I fixed the ID ref and resubmitted application to the store :)
