### ISSUE TITLE
Wrong string slicing when reminding another user and [when] option is not declared

### ISSUE THREAD

**Issue by tassoevan** [croz-ltd/Rocket.Chat.App-Remind#3]
Works fine:

```
/remind @tasso.evangelista to go out and take long walk in 10 minutes
```

```
👍 I will remind you to "to go out and take long walk" in "10 minutes".
```

Poorly sliced case:

```
/remind @tasso.evangelista to go out and take long walk
```

```
👍 I will remind you to "@tasso.evangelista " in "sso.evangelista to go out and take long walk".
You asked me to remind you to "@tasso.evangelista ".
```

P.S.: This app is amazing! Thank you for making it!

**Comment by mjovanovic0** [comment]
Yeah..

I predict that slicing will be issue...

That is why I implemented TODO from start 🤣 

https://github.com/mjovanovic0/rocketchat-remind-app/blob/51ef3528220623b9535f98adc5e4c4236eb37cab/src/Command/RemindCommand.ts#L35

**Comment by mjovanovic0** [comment]
Also hint, you can user keyword `me` instead of your own `@` tag

**Comment by tassoevan** [comment]
> Also hint, you can user keyword `me` instead of your own `@` tag

True! But it's somewhat broken too:

```
👍 I will remind you to "me " in "to go out and take long walk".
You asked me to remind you to "me ".
```

**Comment by mjovanovic0** [comment]
Can you provide exact command you are typing?

**Comment by tassoevan** [comment]
```
/remind me to go out and take long walk
```

**Comment by mjovanovic0** [comment]
Ahh I see. You are missing time component and parsing the message fail to find when you what him to remind you.

I added some checks to avoid this issue (proper slicing still needs to be implemented) and if it fail to find time component will send you nice message about that:

```
Fail to understand when you want me to remind you. 😕
```
