### ISSUE TITLE
Cannot install Remind Me from Marketplace

### ISSUE THREAD

**Issue by tuxmartin** [croz-ltd/Rocket.Chat.App-Remind#5]
Hi, I have problem with installation on my Rocket.Chat server (snap, 3.8.2, Debian 10).

Can you please help me?

![image](https://user-images.githubusercontent.com/1219067/101242880-adc59e00-36fc-11eb-944a-41f0a71f25b2.png)

**Comment by mjovanovic0** [comment]
It looks like Rocket.Chat related issue, not the app issue.

From logs I can see:
```
server.js:204 API ➔ debug GET: /api/apps?buildExternalUrl=true&appId=29d6e7df-d111-4b24-835c-c580fe511e2f&purchaseType=&details=false
server.js:204 API ➔ debug Failure {
  statusCode: 400,
  body: { error: 'Invalid purchase type', success: false }
}
```

**Comment by stenrose** [comment]
Having same issue. Other apps (tested with Math by Reiske.Tech) works just fine to install from Marketplace.

Running 3.8.1 in a Docker container.

**Comment by Sys-Admin889** [comment]
Also me have the same problem.

**Comment by shoei101** [comment]
same issue as well

Running 3.8.3 snap

**Comment by r-souza** [comment]
Same here.

Running version 3.9.1

**Comment by lahouazi-riad** [comment]
Same here.

Running version 3.8.3

**Comment by jwSPIX** [comment]
Cannot install either. Has anyone manual installed?

3.8.3 Snap
--

**Comment by saschafoerster** [comment]
Newest version, 3.9.3, docker, has the same issue.

**Comment by shoei101** [comment]
has anyone got it to install correctly?

**Comment by jwalker5006** [comment]
> It looks like Rocket.Chat related issue, not the app issue.
> 
> From logs I can see:
> 
> ```
> server.js:204 API ➔ debug GET: /api/apps?buildExternalUrl=true&appId=29d6e7df-d111-4b24-835c-c580fe511e2f&purchaseType=&details=false
> server.js:204 API ➔ debug Failure {
>   statusCode: 400,
>   body: { error: 'Invalid purchase type', success: false }
> }
> ```

I think the app catalog item needs to have a purchaseType = to buy. And the Api call should included buy in the purchaseType. That should fix it.

I would expect it to be something like
GET: /api/apps?buildExternalUrl=true&appId=29d6e7df-d111-4b24-835c-c580fe511e2f&purchaseType=buy&details=false

And update the app catalog item
<img width="788" alt="RemindMe" src="https://user-images.githubusercontent.com/6217843/103092640-835d5700-45bd-11eb-8328-6e7ee86936ca.png">

**Comment by tuxmartin** [comment]
That would be a great Christmas present 🙂

**Comment by shoei101** [comment]
i was able to install and run the app today!

**Comment by r-souza** [comment]
That's right, today the same version 0.0.1 is working!

**Comment by lazyants** [comment]
I could also install it now, but I will be not remind

```
/remind me about meeting in 2 minutes
```

rocket says 
```
Rocket.Cat @rocket.cat
10:33 AM
👍 I will remind you to "about meeting" in "2 minutes".
```

but nothing happens

**Comment by tuxmartin** [comment]
@lazyants I have the same problem :-(

**Comment by shoei101** [comment]
sorry i should have posted back in this thread, installation was successful...but i'm experiencing the same as @lazyants and @tuxmartin

**Comment by r-souza** [comment]
Same here, installed but nothing happens

**Comment by lahouazi-riad** [comment]
me too, install but nothing happens

**Comment by thejasonfunderburker** [comment]
same, commands like 
/remind me to get reminders to work in 2 minutes 

doesn't have any results, there is no message rom rocket.cat

log says: error: 2021-02-20T09:51:32.082Z Caller: anonymous OR constructors

**Comment by mjovanovic0** [comment]
Hi all,

I just submitted new version of app with the fix for app not working.
Depending on the approval process from Rocket.Chat team, app should be available in a day or two (I hope).

**Comment by shoei101** [comment]
awesome! can't wait to try it out.

**Comment by tuxmartin** [comment]
@mjovanovic0 hi, last week I uninstalled the app.

I don't see it in the marketplace now.

How can I install it again?

**Comment by mjovanovic0** [comment]
I submitted new version of app with the fix for app not working.
Now it is on the Rocket.Chat team and their approval process.

**Comment by tuxmartin** [comment]
@mjovanovic0 do you have any news?

**Comment by tuxmartin** [comment]
@mjovanovic0  do you have any news? :-)

**Comment by tuxmartin** [comment]
@mjovanovic0 do you have any news?
