### ISSUE TITLE
Reminder doesn't appear

### ISSUE THREAD

**Issue by accessfletch** [croz-ltd/Rocket.Chat.App-Remind#7]
As a test, I entered `/remind me to test in 10 seconds` and received the proper `👍 I will remind you to "to test" in "10 seconds".` response from the bot.

However, no reminder was given, either in the channel I requested from, nor in the DM with the `rocket.cat` bot that is running the app.

**Comment by shoei101** [comment]
Well after finally able to get it installed and i'm experiencing the exact same thing.  I receive the proper response from the bot, but the reminder never happens.

**Comment by jsalatiel** [comment]
Facing the same issue.
RocketChat 3.8.4

**Comment by vladanminic** [comment]
Same here...
RocketChat server v3.9.0, client v3.1.1

**Comment by tuxmartin** [comment]
I have the same problem :-(

Rocket.Chat SNAP 3.9.3.

**Comment by jsalatiel** [comment]
@mjovanovic0  stiill working on this ?

**Comment by merlin-tc** [comment]
Sadly having the same problem. This would be so useful, hope it does get fixed!
Still running 3.8.0.

**Comment by tuxmartin** [comment]
Hi, do you have any news?

Rocket.Chat version 3.10.5 is still broken :-(

**Comment by robertfromont** [comment]
This is also an issue in 3.11.1

**Comment by mjovanovic0** [comment]
Hi all,

I just submitted new version of app with the fix for app not working.
Depending on the approval process from Rocket.Chat team, app should be available in a day or two (I hope).

**Comment by jsalatiel** [comment]
Was the app removed from market place ?

**Comment by merlin-tc** [comment]
@mjovanovic0 Do you have any infos on why the app was removed from the RocketChat market? Did you get any notification on why it happened?
